# The URL the site will be built for
base_url = "https://example.com"

title = "The Rising of the Shield Hero"

generate_rss = true
compile_sass = false

highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "categories", rss = true, paginate_by=3},
    {name = "tags", rss = true, paginate_by=3},
]

[extra]
author = "Naomi Yuui"
bbt_blog_menu = [
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/projects", name = "Projects"},
    {url = "$BASE_URL/journal", name = "Journal"},
    {url = "$BASE_URL/contact", name = "Contact"}
]

bbt_blog_social = [
    {url = "https://twitter.com", icon="fab fa-twitter"},
    {url = "$BASE_URL/rss.xml", icon="fas fa-rss"}
]